[package]
authors = ["The Rust Project Developers"]
name = "unwind"
version = "0.0.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/rust.git"
edition = "2018"
include = [
  '/libunwind/*',
]

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
libc = { git = "https://github.com/ivmarkov/libc.git", branch = "version_0.2.98", features = ['rustc-dep-of-std'], default-features = false }
compiler_builtins = "0.1.0"
cfg-if = "0.1.8"

[build-dependencies]
cc = { version = "1.0.1" }

[features]
llvm-libunwind = []
system-llvm-libunwind = []
